development:
  adapter: postgresql
  encoding: unicode
  database: appname_development
  pool: 5
  host: localhost
  port: 5432
  timeout: 5000
  username: postgres
  password: 31415926

test:
  adapter: postgresql
  encoding: unicode
  database: appname_test
  pool: 5
  host: localhost
  port: 5432
  timeout: 5000
  username: postgres
  password: 31415926
