# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59c4a96e018f7f19423e9031a32166a27be603eb5683cbda4ba270d5b2bfd7c62072f3b3841540d4b64de7c864f19bb76a7fc5998b71e214e18250efed5119f4

test:
  secret_key_base: 66fff98faf7d9d214ed092e255bb6e2358faf067646aa1ac36f13bd5d943356697d331367e7215359ce75c9b48256ae3480c45ac37232007d15728b3a4d5eb7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
